[package]
name = "ad2vcf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
npyz = "0.8.1"
rust-htslib = "0.44.1"
